export const SET_LOADING = 'SET_LOADING';
export const GET_CONTRIBUTORS = 'GET_CONTRIBUTORS';
export const GET_CONTRIBUTOR = 'GET_CONTRIBUTOR';
export const GET_POSTS = 'GET_POSTS';
export const GET_EVENTS = 'GET_EVENTS';
export const SET_LOADINGFOREVENTS = 'SET_LOADINGFOREVENTS';